# Generated by Django 5.0.1 on 2024-01-06 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoiceID', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('customerName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('detailsID', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('price', models.IntegerField()),
                ('invoiceID', models.ForeignKey(db_column='invoiceID', on_delete=django.db.models.deletion.CASCADE, to='api.invoice')),
            ],
        ),
    ]
